import type { YTProColumns } from '@/components/YTProTable/typing';
import { connectStatus } from '@/utils/dict';
import type { ElectricGenerateInfo } from './type';
import { formatMessage } from '@/utils';

export const columns: YTProColumns<ElectricGenerateInfo>[] = [
  {
    title: formatMessage({ id: 'common.deviceName', defaultMessage: '设备名称' }),
    dataIndex: 'deviceName',
    width: 120,
    ellipsis: true,
    hideInSearch: true,
  },
  {
    title: formatMessage({ id: 'common.deviceCode', defaultMessage: '设备编码' }),
    dataIndex: 'deviceId',
    width: 150,
    ellipsis: true,
    hideInSearch: true,
  },
  {
    title: formatMessage({ id: 'common.equipmentSerial', defaultMessage: '设备序列号' }),
    dataIndex: 'sn',
    hideInSearch: true,
    width: 150,
  },
  {
    title: formatMessage({ id: 'siteMonitor.owningSite', defaultMessage: '所属站点' }),
    dataIndex: 'siteName',
    width: 120,
    ellipsis: true,
    hideInSearch: true,
  },
  {
    title: formatMessage({ id: 'siteMonitor.communicationStatus', defaultMessage: '通信状态' }),
    dataIndex: 'connectStatus',
    valueEnum: connectStatus,
    width: 120,
    ellipsis: true,
  },
  {
    title: `${formatMessage({ id: 'common.power', defaultMessage: '功率' })}(kW)`,
    dataIndex: 'p',
    width: 120,
    ellipsis: true,
    hideInSearch: true,
  },
  {
    title: `${formatMessage({ id: 'common.groupString', defaultMessage: '组串' })}1`,
    dataIndex: 'ipv1',
    width: 150,
    hideInSearch: true,
    ellipsis: true,
  },
  {
    title: `${formatMessage({ id: 'common.groupString', defaultMessage: '组串' })}2`,
    dataIndex: 'ipv2',
    width: 150,
    hideInSearch: true,
    ellipsis: true,
  },
  {
    title: `${formatMessage({ id: 'common.groupString', defaultMessage: '组串' })}3`,
    dataIndex: 'ipv3',
    width: 150,
    hideInSearch: true,
    ellipsis: true,
  },
  {
    title: `${formatMessage({ id: 'common.groupString', defaultMessage: '组串' })}4`,
    dataIndex: 'ipv4',
    width: 150,
    hideInSearch: true,
    ellipsis: true,
  },
  {
    title: `${formatMessage({ id: 'common.groupString', defaultMessage: '组串' })}5`,
    dataIndex: 'ipv5',
    width: 150,
    hideInSearch: true,
    ellipsis: true,
  },
  {
    title: `${formatMessage({ id: 'common.groupString', defaultMessage: '组串' })}6`,
    dataIndex: 'ipv6',
    width: 150,
    hideInSearch: true,
    ellipsis: true,
  },
  {
    title: `${formatMessage({ id: 'common.groupString', defaultMessage: '组串' })}7`,
    dataIndex: 'ipv7',
    width: 150,
    hideInSearch: true,
    ellipsis: true,
  },
  {
    title: `${formatMessage({ id: 'common.groupString', defaultMessage: '组串' })}8`,
    dataIndex: 'ipv8',
    width: 150,
    hideInSearch: true,
    ellipsis: true,
  },
  {
    title: `${formatMessage({ id: 'common.groupString', defaultMessage: '组串' })}9`,
    dataIndex: 'ipv9',
    width: 150,
    hideInSearch: true,
    ellipsis: true,
  },
  {
    title: `${formatMessage({ id: 'common.groupString', defaultMessage: '组串' })}10`,
    dataIndex: 'ipv10',
    width: 150,
    hideInSearch: true,
    ellipsis: true,
  },
  {
    title: `${formatMessage({ id: 'common.groupString', defaultMessage: '组串' })}11`,
    dataIndex: 'ipv11',
    width: 150,
    hideInSearch: true,
    ellipsis: true,
  },
  {
    title: `${formatMessage({ id: 'common.groupString', defaultMessage: '组串' })}12`,
    dataIndex: 'ipv12',
    width: 150,
    hideInSearch: true,
    ellipsis: true,
  },
];
