import type { YTProColumns } from '@/components/YTProTable/typing';
import { connectStatus } from '@/utils/dictionary';
import type { ElectricGenerateInfo } from './type';

export const columns: YTProColumns<ElectricGenerateInfo>[] = [
  {
    title: '设备ID',
    dataIndex: 'deviceId',
    width: 150,
    ellipsis: true,
    hideInSearch: true,
  },
  {
    title: '所属站点',
    dataIndex: 'siteName',
    width: 120,
    ellipsis: true,
    hideInSearch: true,
  },
  {
    title: '设备名称',
    dataIndex: 'deviceName',
    width: 120,
    ellipsis: true,
    hideInSearch: true,
  },
  {
    title: '通信状态',
    dataIndex: 'connectStatus',
    valueEnum: connectStatus,
    width: 120,
    ellipsis: true,
  },
  {
    title: '功率(kW)',
    dataIndex: 'p',
    width: 120,
    ellipsis: true,
    hideInSearch: true,
  },
  {
    title: '设备SN',
    dataIndex: 'sn',
    hideInSearch: true,
    width: 150,
  },
  {
    title: '组串1',
    dataIndex: 'ipv1',
    width: 150,
    hideInSearch: true,
    ellipsis: true,
  },
  {
    title: '组串2',
    dataIndex: 'ipv2',
    width: 150,
    hideInSearch: true,
    ellipsis: true,
  },
  {
    title: '组串3',
    dataIndex: 'ipv3',
    width: 150,
    hideInSearch: true,
    ellipsis: true,
  },
  {
    title: '组串4',
    dataIndex: 'ipv4',
    width: 150,
    hideInSearch: true,
    ellipsis: true,
  },
  {
    title: '组串5',
    dataIndex: 'ipv5',
    width: 150,
    hideInSearch: true,
    ellipsis: true,
  },
  {
    title: '组串6',
    dataIndex: 'ipv6',
    width: 150,
    hideInSearch: true,
    ellipsis: true,
  },
  {
    title: '组串7',
    dataIndex: 'ipv7',
    width: 150,
    hideInSearch: true,
    ellipsis: true,
  },
  {
    title: '组串8',
    dataIndex: 'ipv8',
    width: 150,
    hideInSearch: true,
    ellipsis: true,
  },
  {
    title: '组串9',
    dataIndex: 'ipv9',
    width: 150,
    hideInSearch: true,
    ellipsis: true,
  },
  {
    title: '组串10',
    dataIndex: 'ipv10',
    width: 150,
    hideInSearch: true,
    ellipsis: true,
  },
  {
    title: '组串11',
    dataIndex: 'ipv11',
    width: 150,
    hideInSearch: true,
    ellipsis: true,
  },
  {
    title: '组串12',
    dataIndex: 'ipv12',
    width: 150,
    hideInSearch: true,
    ellipsis: true,
  },
];
