pages:
  stage: deploy
  cache:
    key:
      files:
        - pnpm-workspace.yaml
      prefix: pnpm
    paths:
      - node_modules/
  script:
    - pnpm install
    - pnpm build-editor
    - cp -a dist/. public/
  artifacts:
    paths:
      - public
  rules:
    - if: $CI_COMMIT_BRANCH == $CI_DEFAULT_BRANCH
