ls:
  packages/**/*:
    .vue: PascalCase
    .js: kebab-case
    .config.js: lowercase
    .ts: camelCase | PascalCase
    .d.ts: camelCase | kebab-case
    .mock.ts: camelCase

ignore:
  - dist
  - test
  - .babelrc.js
  - .eslintrc.js
  - .prettierrc
  - .github
  - .git
  - node_modules
