# 基础镜像
FROM busybox:stable

RUN rm -rf /home/yt/projects/
# 复制html文件到路径
ADD yt-ui.tar.gz /home/yt/bak/

CMD [ \
    "rm",\
    "-rf",\
    "/home/yt/projects/yt-ui/*",\
    "&",\
    "mv",\
    "/home/yt/bak/yt-ui/*",\
    "/home/yt/projects/yt-ui/"\
]
